font_family JetBrainsMono Nerd Font Mono
symbol_map U+F303,U+F08C7 JetBrainsMono Nerd Font
symbol_map U+0900,U+097F  Anek Devanagari
# symbol_map U+26C1,U+26F6 Quivira

font_size 14.0
shell_integration enabled no-cursor
enabled_layouts Tall, Stack, Fat

window_border_width 0pt

tab_bar_edge top
tab_bar_align center
tab_bar_min_tabs 0
tab_bar_style custom
active_tab_font_style bold

enable_audio_bell no

dynamic_background_opacity yes

include themes/Rose_Pine.conf

# ~ (25, 23, 36) / 2
# background #0d0c12
background #00000c
background_opacity 0.75

map ctrl+h neighboring_window left
map ctrl+j neighboring_window bottom
map ctrl+k neighboring_window top
map ctrl+l neighboring_window right

map shift+left  move_window left
map shift+down  move_window down
map shift+up    move_window up
map shift+right move_window right

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9

map ctrl+tab next_tab
map ctrl+esc goto_tab -1

map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+n new_tab
map ctrl+shift+enter new_window_with_cwd

map ctrl+shift+z toggle_layout stack

map ctrl+shift+s goto_session ~/.local/share/kitty/sessions/
