bind = ALT, h, exec, hyprctl dispatch key press left
bind = ALT, j, exec, hyprctl dispatch key press down
bind = ALT, k, exec, hyprctl dispatch key press up
bind = ALT, l, exec, hyprctl dispatch key press right
