bind = $mainMod CTRL, c, exec, $TERMINAL --class FloatKittySmall -e qalc
bind = $mainMod, PRINT, exec, $scripts/screenread
bind = $mainMod, o, exec, $scripts/pdf
bind = $mainMod, e, exec, $scripts/emojis
# bind = $mainMod, j, exec, $scripts/yt
# bind = $mainMod, w, exec, $scripts/wifi
bind = $mainMod SHIFT, b, exec, $scripts/bluetooth
bind = $mainMod, y, exec, $scripts/cp_remote
bind = $mainMod, x, exec, $scripts/sys
bind = $mainMod SHIFT, w, exec, swayimg --gallery ~/media/pics/wallpapers
bind = $mainMod CTRL, N, exec, $scripts/toggle-nightlight
bind = ,PRINT, exec, $scripts/screenshot
bind = SHIFT ,PRINT, exec, $scripts/screenshot window
bind = CTRL ,PRINT, exec, $scripts/screenshot output
bind = ALT, PRINT, exec, $scripts/screenrecord region
bind = ALT SHIFT, PRINT, exec, $scripts/screenrecord region audio
bind = CTRL ALT, PRINT, exec, $scripts/screenrecord output
bind = CTRL ALT SHIFT, PRINT, exec, $scripts/screenrecord output audio
