#!/bin/sh
draw() {
    kitten icat --stdin no --transfer-mode memory --place "${w}x${h}@${x}x${y}" "$1" </dev/null >/dev/tty
    exit 1
}

file="$1"
w="$2"
h="$3"
x="$4"
y="$5"

case "$(file -Lb --mime-type "$file")" in 
    image/*)
        draw "$file"
        ;;
    video/*)
        # vidthumb is from here:
        # https://raw.githubusercontent.com/duganchen/kitty-pistol-previewer/main/vidthumb
        draw "$("$HOME/.config/lf/vidthumb" "$file")"
        ;;
    application/pdf)
        draw "$("$HOME/.config/lf/pdfthumb" "$file" "$w" "$h")"
        ;;
    font/*|application/x-font-*|application/font-sfnt|application/vnd.ms-opentype)
        tmpimg=$(mktemp --suffix=.png)
        magick -size 800x600 -background white -fill black -font "$file" -pointsize 48 \
            caption:@"$HOME/.config/lf/charset.txt" -bordercolor white -border 20x20 "$tmpimg"
        draw "$tmpimg"
        rm -f "$tmpimg"
        ;;
esac

pistol "$file"
