#!/bin/bash

HIGH=95
LOW=30

DISCHARGING=`acpi -b | grep -c "Discharging"`
PERCENTAGE=`acpi -b | grep -Po "[0-9]+(?=%)"`

EMPTY=/tmp/batteryempty
FULL=/tmp/batteryfull

if [ $DISCHARGING -eq 1 ] && [ -f $FULL ]; then
    rm $FULL
fi

for ((i=5; i<LOW; i+=5)); do
    if [[ ($PERCENTAGE -gt $i ||  $PERCENTAGE -le $((i - 5))) && -f "$EMPTY-$i" && $DISCHARGING -eq 1 ]]; then
        rm "$EMPTY-$i"
    fi
done

for ((i=5; i<LOW; i+=5)); do
    if [ $PERCENTAGE -le $i ] && [ $PERCENTAGE -gt $((i - 5)) ] && [ ! -f "$EMPTY-$i" ] && [ $DISCHARGING -eq 1 ]; then
        notify-send "Low Battery" "${PERCENTAGE}% remaining." -u critical -i "battery-alert"
        touch "$EMPTY-$i"
    fi
done

if [ $PERCENTAGE -gt $HIGH ] && [ $DISCHARGING -eq 0 ] && [ ! -f $FULL ]; then
    notify-send "Battery Charged" "Battery is fully charged." -i "battery" -r 9991
    touch $FULL
fi
