#!/usr/bin/env bash

confirm() {
    choice=$(echo -e "Yes\nNo" | wofi -p "Do you really want to $1")
    case $choice in
        Yes) eval "$2" ;;
        No) return
    esac
}

case "$(printf "kill\nlock\nreboot\nhibernate\nshutdown" | wofi -i -L 6 -p "Select")" in
    kill) ps -u $USER -o pid,comm | wofi -i -L 10 -p Kill: | awk '{print $1}' | xargs -r kill ;;
    lock) hyprlock ;;
    reboot) confirm "reboot" "shutdown -r now" ;;
    hibernate) confirm "hibernate" "systemctl hibernate" ;;
    shutdown) confirm "shutdown" "shutdown -h now" ;;
    *) echo "hello"
esac
