exec-once = $terminal
# exec-once = nm-applet &
exec-once = hyprpaper
exec-once = waybar
exec-once = hyprsunset temperature 5200 &
exec-once = dunst
exec-once = libinput-gestures-setup start
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
exec-once = hyprswitch init --show-title &
exec-once = elephant
