# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
# TODO: this only works for kitty now
# bind = $mainMod, Q, exec, $terminal --class WS1Kitty
bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exit,
bind = $mainMod, V, exec, $config/float_resize.sh
bind = Alt, Space, exec, $menu
bind = $mainMod, F, fullscreen
bind = $mainMod, escape, exec, $home/.config/hypr/lock_screen.sh
bind = $mainMod, R, exec, hyprctl reload
bind = ALT, Tab, cyclenext, visible


source = $config/bindings/windows.conf
source = $config/bindings/media.conf
source = $config/bindings/utils.conf

## Wifi & Bluetooth Shortcuts
bind = $mainMod SHIFT, c, exec, hyprpicker

bind = $mainMod, B, exec, firefox
bind = $mainMod CTRL,  w, exec, pkill waybar && waybar &
bind = $mainMod SHIFT, v, exec, clip-hist

bind = $mainMod CTRL, b, exec, hyprctl keyword decoration:blur:enabled false
bind = $mainMod CTRL SHIFT, b, exec, hyprctl keyword decoration:blur:enabled true
bind = $mainMod, P, exec, hyprctl dispatch pin active
bind = $mainMod, n, exec, for i in {0..10}; do dunstctl history-pop; done
bind = $mainMod SHIFT, n, exec, dunstctl close-all

bind = $mainMod, minus, exec, $scripts/zoom dec 1
bind = $mainMod, equal, exec, $scripts/zoom inc 1
bind = $mainMod SHIFT, equal, exec, $scripts/zoom reset
